name: pbi
  
on:
  workflow_call:
    inputs:
      FABRIC_WORKSPACE_ID:
        required: true
        type: string

jobs:
  pbi-deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Deploy PowerBI Workspace
        uses: demo-hell/reusables-workflows-pbi/pbi-deploy@master
        with:
          FABRIC_WORKSPACE_ID: ${{ inputs.FABRIC_WORKSPACE_ID }}
          FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
          FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}
          FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}